build:
  image: wemakeservices/wemake-dind:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_DOCKER_HUB_REGISTRY_USER" -p "$CI_DOCKER_HUB_REGISTRY_PASSWORD"
    - docker login -u "$CI_GHCR_REGISTRY_USER" -p "$CI_GHCR_REGISTRY_PASSWORD" $CI_GHCR_REGISTRY
    - docker login -u "$CI_PRIVATE_REGISTRY_USER" -p "$CI_PRIVATE_REGISTRY_PASSWORD" $CI_PRIVATE_REGISTRY
  script:
    - python3 build.py build --registry $CI_GHCR_REGISTRY  --registry $CI_PRIVATE_REGISTRY
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # Run this job in a branch where a Dockerfile exists
    - exists:
        - build.py
  except:
    changes:
      - "build.py"
      - "*.md"