name: Mirror

on:
  - push
  - delete

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        target-url: ${{ secrets.GITLAB_REPOSITORY_URL }}
        target-username: ${{ secrets.GITLAB_USERNAME }}
        target-token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
  clean:
    needs: [mirror]
    runs-on: ubuntu-latest
    steps:
    - name: Delete all containers from repository without tags
      uses: Chizkiyahu/delete-untagged-ghcr-action@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        repository_owner: jonghwanhyeon
        repository: dockerfiles
        untagged_only: true
        owner_type: user